
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Event_Management_System
    username: root
    password: Pratik@1
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    # properties:
    #    hibernate:
    #      format_sql: true